#cloud-config
groups:
  - ubuntu: [root,sys]
  - cloud-users

users:
  - name: samrap
    gecos: samrap
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: [sudo]
    shell: /bin/bash
    lock_passwd: true

write_files:
  - path: /etc/ssh/sshd_config
    content: |
      Port 22
      PermitRootLogin no
      PasswordAuthentication no
      ChallengeResponseAuthentication no
      ChallengeResponseAuthentication no
      UsePAM yes
      X11Forwarding yes
      PrintMotd no
      AcceptEnv LANG LC_*
      Subsystem       sftp    /usr/lib/openssh/sftp-server

packages:
  - libnss3
  - python3
  - python3-pip

runcmd:
  - |
    # Copy the root authorized SSH keys that this droplet was created with.
    if [ -f /root/.ssh/authorized_keys ]; then
      mkdir /home/samrap/.ssh
      cp /root/.ssh/authorized_keys /home/samrap/.ssh/authorized_keys
      chown -R samrap:samrap /home/samrap/.ssh
    fi
